-- Example table for logging BBX boost claims
create table if not exists public.boost_claims (
  id bigint generated by default as identity primary key,
  inserted_at timestamp with time zone default timezone('utc', now()),
  wallet text,
  signature text not null,
  content_url text not null,
  amount_units text not null,
  valid boolean not null
);

alter table public.boost_claims enable row level security;

create policy "Allow read" on public.boost_claims
  for select using (true);

create policy "Allow insert" on public.boost_claims
  for insert with check (true);
