name = "bbx-boost-portal"
main = "server.js"
compatibility_date = "2024-07-01"

[vars]
RPC_URL = "<RPC_URL>"
MINT_ADDRESS = "<MINT_ADDRESS>"
TREASURY_ADDRESS = "<TREASURY_ADDRESS>"
MIN_BBX = "25"
DECIMALS = "9"
SUPABASE_URL = "<SUPABASE_URL>"
SUPABASE_PROJECT_URL = "<SUPABASE_PROJECT_URL>"
SUPABASE_ANON_KEY = "<SUPABASE_ANON_KEY>"
SUPABASE_SERVICE_KEY = "<SUPABASE_SERVICE_KEY>"
