name = "bbx-boost-portal"
main = "server.js"
compatibility_date = "2024-07-01"

[vars]
RPC_URL = "https://api.mainnet-beta.solana.com"
MINT_ADDRESS = "C2zw5LJuJu6jpf84325zrGARwrarN8SrCTg5E12FNg3A"
TREASURY_ADDRESS = "<YOUR_TREASURY_ADDRESS>"
MIN_BBX = "25"
DECIMALS = "9"
SUPABASE_URL = "https://pmlvtovpbfpbrjaexvqh.supabase.co"
SUPABASE_PROJECT_URL = "https://pmlvtovpbfpbrjaexvqh.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtbHZ0b3ZwYmZwYnJqYWV4dnFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NTI3MjUsImV4cCI6MjA3MTMyODcyNX0.k-_Lyqq5_sgqra7pLK5Ccxs7SkWB1orFQoJEIGwjax0"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtbHZ0b3ZwYmZwYnJqYWV4dnFoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTc1MjcyNSwiZXhwIjoyMDcxMzI4NzI1fQ.JJQ9cHYDBjQK63MIEtEs9ueVeZgBm3Hcy_2YXhfRroU"
