name: brickbox
publish_to: 'none'
description: BrickBox — The Modern Vault for Comic Collectors

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  go_router: ^14.2.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.5.0+1
  supabase_flutter: ^2.5.6
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
