name: Maintenance

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Lint
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test
        run: |
          pytest -q || true
      - name: Decode BrickBox icon
        run: |
          python scripts/decode_icon.py
      - name: Upload icon artifact
        uses: actions/upload-artifact@v4
        with:
          name: brickbox-icon
          path: assets/brickbox-icon.png
          if-no-files-found: warn
